export {healthService}  from "./health.Service"
export {upLoadFile}  from "./upload.Service"
export {createFolder}  from "./createFile.Service"
export {getFolders}  from "./getFoldersService"
export {deleteFolder}  from "./deleteFolder.Service"
export {deleteFile}  from "./deleteFile.Service"
export {getQueryData}  from "./quer.Service"